### ISSUE TITLE
CJM program error

### ISSUE THREAD

**Issue by JaroslavMajera** [bobril/bbcore#12]
When we open CJM program, there is an error in console and some elements are not visible. Elements are shown after scroll, but error remains. Its ok with bb.
![bb2 error](https://user-images.githubusercontent.com/8265465/37706609-6f5b2b3e-2d00-11e8-81ab-e8bcf0480e56.png)

**Comment by svatal** [comment]
aside from the toUpperCase error, the source maps seems broken

**Comment by Bobris** [comment]
Fixed broken sourcemaps. Still someone needs to debug that toUpperCase problem or show it to me how to reproduce.

**Comment by svatal** [comment]
Thank you, now we can see the problem (still examining the source of it though).

**Comment by Bobris** [comment]
Let me know if you need help

**Comment by svatal** [comment]
It seems to be about missing translation (the translation file contains only 3 items for this particular string, 4 otherwise)
- bb2 returns undefined in this case
- bb returns the original english string
