### ISSUE TITLE
Subsequent recompilations fail when d.ts files are referenced in specs

### ISSUE THREAD

**Issue by tomasdeml** [bobril/bbcore#13]
There seems to be a bug in the compilation cache that manifests itself when `d.ts` files are referenced in jasmine specs (see the attached `src/spec/test.spec.ts` file). The bug affects incremental compilation (triggered by a file modification) and also recompilation (after restart of bb2) of jasmine specs. 

**bb2 version 0.27.2**

### Repro steps
1. Clean bb2 caches by nuking the cache directories under `C:\Users\<user>\.bbcore\tools`
2. Build the attached [repro.zip](https://github.com/bobril/bbcore/files/1897473/repro.zip) sample with bb2 - the compilation and specs pass
3. Restart bb2 and build the sample again - the compilation fails on:
> src/spec/test.spec.ts(7,16): error TS2551: Property 'toBeOk' does not exist on type 'Matchers<{}>'. Did you mean 'toBe'?
> Build done in 2.1 with 1 error and no warnings and has 9 files
4. Stop bb2 and and clean its caches
2. Build the sample again - the compilation and specs pass again

#### Alternative scenario
1. Clean bb2 caches by nuking the cache directory under `C:\Users\<user>\.bbcore\tools`
2. Build the attached repro sample with bb2 - the compilation and specs pass
3. Modify `test.spec.ts` by adding a new line and save it - the compilation fails on:
> src/spec/test.spec.ts(7,16): error TS2551: Property 'toBeOk' does not exist on type 'Matchers<{}>'. Did you mean 'toBe'?
> Build done in 2.1 with 1 error and no warnings and has 9 files
4. Stop bb2 and and clean its caches
2. Build the sample again - the compilation and specs pass again

#### Another scenario
1. Clean bb2 caches by nuking the cache directory under `C:\Users\<user>\.bbcore\tools`
2. Build the attached repro sample with bb2 - the compilation and specs pass
3. Modify `index.ts` by adding a new line and save it - the compilation and specs pass
3. Modify `test.spec.ts` by adding a new line and save it - the compilation fails on:
> src/spec/test.spec.ts(7,16): error TS2551: Property 'toBeOk' does not exist on type 'Matchers<{}>'. Did you mean 'toBe'?
> Build done in 2.1 with 1 error and no warnings and has 9 files
4. Stop bb2 and and clean its caches
2. Build the sample again - the compilation and specs pass again

**Comment by Bobris** [comment]
Problem is that there are 2 files with same name with just different extensions .ts and .d.ts. To speed up compilation I creating .d.ts file out of .ts which overshadows original .d.ts making next compilation fail.
I am not sure I need to fix this when workaround is so simple just rename .d.ts file and reference comment.

**Comment by Bobris** [comment]
Added detection of spec.d.ts files which solve this problem nicely.
