### ISSUE TITLE
Sharing source code from Win to Debian container

### ISSUE THREAD

**Issue by BartosStore** [bobril/bbcore#26]
Hi,
we are trying to create an portable build environment for build/test servers (build tools in docker container on **debian** and project files shared from **Win**). 

When we run build bbcore fails on creating symlinks. We can simply force the yarn to not create symlinks.

Is it possible to add **--no-bin-links** option for yarn install command (enabled on flag)?

`
yarn install --no-bin-links
`

**Comment by Bobris** [comment]
BTW: As workaround you could just forbid running of yarn from bbcore and run it yourself ...

**Comment by Bobris** [comment]
Implemented using environmental variable `BBCoreNoLinks` which is more "docker" way ... Didn't tested hope it will work.
