### ISSUE TITLE
Required the internet connection

### ISSUE THREAD

**Issue by JanVargovsky** [bobril/bbcore#29]
In case that I dont have the internet available and I start bb2 it tries to download the latest version from the GitHub. Is it possible to add fallback in case of no connection and try to start current latest version stored locally?

**Comment by Bobris** [comment]
Strange it should already work like that:
https://github.com/bobril/bbcore/blob/52d97328cbf5ef45de5c8d851be6287dc8f6e4c0/tools/bbcorenpm/index.ts#L272

**Comment by Bobris** [comment]
But you are right reproduced problem ...

**Comment by Bobris** [comment]
You need to upgrade bobril-build-core npm to 1.5.0:

    yarn global upgrade bobril-build-core
