### ISSUE TITLE
"bb test" should allow filtering tests

### ISSUE THREAD

**Issue by scottis** [bobril/bbcore#37]
[Karma](https://karma-runner.github.io), a popular Jasmine test runner, supports filtering Jasmine tests by a pattern via the [`karma-jasmine`](https://github.com/karma-runner/karma-jasmine#configuration) adapter. In Karma, starting tests that match a pattern via the CLI looks like the following.

```bash
karma run -- --grep=<pattern>
```

Jasmine exposes [env.specFilter](https://jasmine.github.io/tutorials/custom_boot#section-7) as a way to filter tests at runtime, so this could probably be implemented in a way that is similar to [`karma-jasmine`'s implementation](https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L317).

**Does `bbcore` plan to support a similar feature?**

**Comment by Bobris** [comment]
Currently it is not customizable. I have it in plan, but not in really short term one. Usually just `fdecribe` and `fit` are enough during development.

**Comment by scottis** [comment]
@Bobris 

Now that I think about it, this might also be useful in interactive mode (similar to `karma-jasmine`'s `autoWatch: true` combined with `singleRun: false`).

**Comment by Bobris** [comment]
For interactive mode it would need to be editable from bb web. And for that it would also help to move SpecFilter into StartTest method.
