### ISSUE TITLE
exception on begin compilation

### ISSUE THREAD

**Issue by Lisaj** [bobril/bbcore#4]
![image](https://user-images.githubusercontent.com/307575/35728013-71223a86-080a-11e8-8369-9b3e09a6ae2e.png)
![image](https://user-images.githubusercontent.com/307575/35728053-938c1204-080a-11e8-9c7f-cbf855415b52.png)

**Comment by Lisaj** [comment]
I try it with version 0.5.0, 0,6,1 and 0.8.0 with same result

**Comment by Bobris** [comment]
This was reason I had to upgrade to Typescript 2.7.1 ... Need to test it again.

**Comment by Bobris** [comment]
Ouch you are right, I somehow forget include TS upgrade. It still uses 2.6.2 which has this bug.

**Comment by Bobris** [comment]
Try new version ...

**Comment by Bobris** [comment]
Tried myself there is still something to fix. Wait another day.

**Comment by Lisaj** [comment]
Version 0.9.1 throw this exception on begin compilation
![image](https://user-images.githubusercontent.com/307575/35844938-378a2492-0b10-11e8-99ec-9ba33985a29d.png)
![image](https://user-images.githubusercontent.com/307575/35844946-46e6b702-0b10-11e8-8131-20a7536b8109.png)

**Comment by Bobris** [comment]
it is fixed by development.
