### ISSUE TITLE
Empty test result file generated when using -o and --dir options simultaneously

### ISSUE THREAD

**Issue by LukasNajman** [bobril/bbcore#49]
When running command `bb2 test -o /home/me/testResults.xml --dir /home/me/bundle` the testResults.xml file is missing the list of executed tests. Only xml header `<?xml version="1.0" encoding="utf-8"?>` is present in the file.

Removing the --dir option, the list of executed tests is present in the testResults.xml as expected.

**Comment by straakaa** [comment]
It's not working from version 2.5.1.

**Comment by Bobris** [comment]
Should be fixed in 2.5.4
