### ISSUE TITLE
Can we propagate "yarn install" options through the bb build?

### ISSUE THREAD

**Issue by karelsteinmetz** [bobril/bbcore#50]
I would like to use "yarn install --ignore-optional" because do mess in build logs.
So can we set it by default? I can prepare PR because was looking around and possibilities.

**Comment by Bobris** [comment]
Done https://github.com/bobril/bbcore/commit/c5045ea41dd018c417f0df5510768436236acdc6#diff-25c3365e053c75c300a80c405053c2159a9d2bebddc9b0395c472f7ca8991016R110
