### ISSUE TITLE
bb command always terminates after printing "Bobril-build core running"

### ISSUE THREAD

**Issue by tomaszalesak** [bobril/bbcore#54]
https://github.com/bobril/bbcore/blob/7a3d7c80100724719550503f9341ca598cf508b5/tools/bbcorenpm/index.ts#L395

After this line of code, bb command always terminates with return code 0. Happens only on MacOS ARM64.

bbcore version: 1.61.0
OS: MacOS arm64

**Comment by Bobris** [comment]
Thanks for reporting. Don't have access to MacOS ARM64 myseld, so it was really blind try. Trying to investigate reason with friend who have it.

**Comment by karasek** [comment]
probably linked to code signing:

```
sudo codesign -v ../../.bbcore/1.61.0/bb
../bbcore/bb/bin/Release/1.61.0/bb: code object is not signed at all
In architecture: arm64
```

when called on localy built bb (is working properly) not signed explicitly with any key, got:

`sudo codesign -v ../bbcore/bb/bin/Release/net6.0/osx-arm64/bb`
(no output)

after removing signature from localy built bb

```
sudo codesign --remove-signature ../bbcore/bb/bin/Release/net6.0/osx-arm64/bb
sudo codesign -v ../bbcore/bb/bin/Release/net6.0/osx-arm64/bb
../bbcore/bb/bin/Release/net6.0/osx-arm64/bb: code object is not signed at all
In architecture: arm64
```

is no longer working

**Comment by tomaszalesak** [comment]
Well, I referenced the published version 1.61.0, not locally built version. It printed this "Bobril-build core running" and terminated. (Probably terminating somewhere after that line of code from repo.) Does the published version work for you? The locally built version runs just fine.

**Comment by karasek** [comment]
yes, same - locally built version is ok, published is prevented
it is possible to do self sign (allow running on your machine only), think whether could be done during npm install (does not require root)

`codesign -f -s - ../../.bbcore/1.61.0/bb `

**Comment by tomaszalesak** [comment]
Works, thanks.

**Comment by Bobris** [comment]
bb 1.62.0 is signed for Arm64 out of box and should work without manual steps.
