### ISSUE TITLE
Windows 10 notification

### ISSUE THREAD

**Issue by VPrazak** [bobril/bbcore#9]
There is no notification about successfull or failed build as it was in bobril-build.

**Comment by JanVargovsky** [comment]
I will try to do it.

**Comment by JanVargovsky** [comment]
Alright, I've found how to do it via PowerShell, do we have some specific needs how it should look like? I mean the template of the notification.

Initial proposal:
1. "Build was successful" + check mark icon
2. "Build failed" + cross icon

**Comment by Bobris** [comment]
There could be also notification at least for failed tests.

**Comment by JanVargovsky** [comment]
I guess this one can be closed?
